### ISSUE TITLE
Support including data from outside user-data

### ISSUE THREAD

**Issue by adamchainz** [timeoutdigital/treehugger#83]
EC2 user-data has a rather low max size limit, and when used with CloudFormation it's restricted further to 4096 characters as that's the max size of a parameter there. An encrypted variable in treehugger YAML consumes 200+ bytes, so with only about 15 encrypted parameters we can hit the limit.

It would be nice if the treehugger YAML could support an include statement to go fetch the data from other sources. The most natural AWS'y one is S3. Then a deploy with Cloudformation can just go dump the treehugger file on S3 before updating the stack with the S3 URL (bucket + key + version id) that treehugger sees and fetches. Since treehugger can be run multiple times, it would be good to cache the fetch from S3 to avoid hitting S3 on every single invocation.

I'm imagining the user-data ending up looking like:

```yaml
treehugger:
  include:
  - s3://mybucket/mykey?versionId=abc123
  SOME_OTHER_VAR: 123
  TREEHUGGER_STAGE: production
```

Then when it runs treehugger would fetch all the included files, and merge them all, before continuing.
